# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a38977173d5fc60427da11255ffda44777c4402f3ba5060099d84559913e061677e1a188e97e975c8844b460d8f636ce48a47b2217a206a619d717006d301b47

test:
  secret_key_base: 8e5fb5c3f76b577b9accc9b6c03aa88980d7610b3abd23f86b9640f6b01652fa3d0d30f5574503b94110b196f5e179a52a661c10378c117d55bba0c6a75572ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
